inherit_from: .rubocop_todo.yml

Style/AccessorMethodName:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

#see https://github.com/bbatsov/rubocop/issues/1747
Style/SpecialGlobalVars:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Exclude:
    - 'archive.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'archive.rb'

Lint/UselessAssignment:
  Exclude:
    - 'archive.rb'

Metrics/ParameterLists:
  Exclude:
    - 'archive.rb'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'archive.rb'