inherit_from: .rubocop_todo.yml

Style/AccessorMethodName:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

#see https://github.com/bbatsov/rubocop/issues/1747
Style/SpecialGlobalVars:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3

Metrics/CyclomaticComplexity:
  Exclude:
    - 'archive/**/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'archive/**/*'

Lint/UselessAssignment:
  Exclude:
    - 'archive/**/*'

Metrics/ParameterLists:
  Exclude:
    - 'archive/**/*'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'archive/**/*'

Lint/NestedMethodDefinition:
  Exclude:
    - 'archive/**/*'

Lint/UnreachableCode:
  Exclude:
    - 'archive/**/*'

Style/FileName:
  Exclude:
    - 'archive/**/*'

Style/GuardClause:
  Exclude:
    - 'archive/**/*'

Style/BracesAroundHashParameters:
  Enabled: false

#https://github.com/bbatsov/rubocop/issues/3207
Style/InfiniteLoop:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/MethodLength:
  Exclude:
    - 'road_grid.rb' #this should be fixed but due to rubocop bug may not be placed in todo
    - 'archive/**/*'
    - 'test.rb'
